version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: peluqueria-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: peluqueria
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
